spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fofanaabou/config-repo.git
          timeout: 5
          clone-on-start: true
          force-pull: true
          basedir: config-repo
          default-label: master

server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
