spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fofanaabou/config-repo
          timeout: 5
          clone-on-start: true
          force-pull: true
          default-label: master

server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

logging:
  level:
    web: debug
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"